openapi: 3.1.0
info:
  title: Gulfshore News API
  description: Fetches the latest Gulfshore commercial real estate news headlines and URLs.
  version: 1.0.0
servers:
  - url: https://gulfshore-news-api.onrender.com/news
    description: Live API server
paths:
  /news:
    get:
      operationId: getNewsHeadlines
      summary: Get latest commercial real estate news
      description: Fetches the latest news headlines from Gulfshore Business.
      responses:
        "200":
          description: A JSON object containing news headlines and their URLs.
          content:
            application/json:
              schema:
                type: object
                properties:
                  news:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                          description: The news headline.
                        url:
                          type: string
                          description: The URL to the news article.
